
# main nav links
[[main]]
identifier = "email"
name = "Email"
url = "mailto:max@maxfruehauf.com"
weight = 1

[[main]]
identifier = "cv"
name = "Resume"
url = "/cv/max_cv.pdf"
weight = 5

# [[main]]
#     identifier = "googlescholar"
#     name = "Google Scholar"
#     url = "https://scholar.google.com"
#     weight = 3

[[main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/rasaford"
weight = 2


[[main]]
identifier = "Linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/mfruehauf/"
weight = 4

[[main]]
identifier = "twitter"
name = "X"
url = "https://x.com/FruehaufMax"
weight = 4
